(defvar cool-fg       "#000000")
(defvar cool-bg       "#EDEDED")
(defvar cool-grey     "#DEDFDF")
(defvar cool-green-0  "#4CB64A")
(defvar cool-yellow-0 "#FEFFBF")
(defvar cool-yellow-1 "#F8D00E")
(defvar cool-red-0    "#f5666d")
(defvar cool-pink-0   "#F74D97")
(defvar cool-pink-1   "#FA519A")
(defvar cool-pink-2   "#FD8DBD")
(defvar cool-purple-0 "#a8799c")
(defvar cool-blue-0   "#5179B5")
(defvar cool-blue-1   "#4F78B5")
(defvar cool-blue-2   "#1C3C79")

(defvar fedora-blue-0  "#00BBFF")
(defvar fedora-blue-1  "#0084C8")
(defvar fedora-blue-2  "#00578E")
(defvar fedora-pink-0  "#FF8CA7")
(defvar fedora-pink-1  "#FF7092")
(defvar fedora-green-1 "#9CBB43")

(defun color-theme-gnome-3-adwaita ()
  "Gnome 3 color theme"
  (interactive)
  (color-theme-install
   (append
    (list 'color-theme-gnome-3-adwaita
	  `((background-color . ,cool-bg)
	    (background-mode . light)
	    (border-color . ,cool-bg)
	    (cursor-color . ,fedora-blue-1)
	    (foreground-color . ,cool-fg)
	    (mouse-color . "black"))
	  `(fringe ((t (:background ,cool-bg))))
	  `(mode-line ((t (:foreground ,cool-fg :background "white"))))
	  ;; `(mode-line-buffer-id ((t (:bold t :foreground ,cool-yellow-1))))
	  `(mode-line-inactive ((t (:foreground ,cool-grey :background ,"white"))))
	  `(minibuffer-prompt ((t (:foreground ,fedora-blue-1 :bold t))))
	  `(region ((t (:background ,cool-yellow-0))))
	  `(dired-header ((t (:bold t :foreground ,fedora-blue-1))))

	  `(font-lock-builtin-face ((t (:bold t :foreground ,cool-red-0))))
	  `(font-lock-comment-face ((t (:foreground ,cool-green-0))))
          `(font-lock-constant-face ((t (:foreground ,cool-red-0))))
	  `(font-lock-doc-face ((t (:foreground ,cool-green-0 :bold t))))
	  `(font-lock-function-name-face ((t (:foreground ,fedora-blue-2 :bold t))))
	  `(font-lock-keyword-face ((t (:bold t :foreground ,cool-blue-0))))
          `(font-lock-preprocessor-face ((t (:foreground ,cool-fg))))
	  `(font-lock-string-face ((t (:foreground ,fedora-pink-1))))
	  `(font-lock-type-face ((t (:foreground ,cool-pink-0 :bold t))))
	  `(font-lock-variable-name-face ((t (:foreground ,fedora-blue-1 :bold t))))
	  `(font-lock-warning-face ((t (:foreground ,cool-red-0 :bold t))))
	  ;;js2-external-variable

	  `(erc-action-face ((t (:foreground ,cool-red-0))))
          `(erc-button ((t (:foreground ,cool-purple-0))))
          `(erc-current-nick-face ((t (:bold t :foreground ,fedora-pink-1))))
          `(erc-error-face ((t (:foreground ,cool-red-0 :bold t))))
          `(erc-input-face ((t (:foreground ,cool-fg))))
          `(erc-keyword-face ((t (:foreground ,cool-red-0))))
          `(erc-my-nick-face ((t (:bold t :foreground ,fedora-pink-0))))
          `(erc-nick-default-face ((t (:bold t :foreground ,fedora-blue-1))))
          `(erc-notice-face ((t (:foreground ,fedora-blue-1))))
          `(erc-prompt-face ((t (:foreground ,cool-fg))))
          `(erc-timestamp-face ((t (:foreground ,cool-green-0))))

	  `(magit-log-sha1 ((t (:foreground ,fedora-pink-1))))
	  `(magit-log-head-label-local ((t (:foreground ,cool-blue-1))))
	  `(magit-log-head-label-remote ((t (:foreground ,cool-green-0))))
	  `(magit-branch ((t (:bold t :foreground ,fedora-blue-1))))
	  `(magit-section-title ((t (:bold t :foreground ,fedora-blue-2))))
	  `(magit-item-highlight ((t (:background ,cool-yellow-0))))
	  `(magit-diff-add ((t (:bold t :foreground ,cool-green-0))))
	  `(magit-diff-del ((t (:bold nil :foreground ,cool-red-0))))

	  `(gnus-group-mail-1-empty ((t (:foreground ,fedora-blue-2))))
	  `(gnus-group-mail-1 ((t (:bold t :foreground ,cool-blue-1))))
	  `(gnus-group-mail-2-empty ((t (:foreground ,fedora-blue-2))))
	  `(gnus-group-mail-2 ((t (:bold t :foreground ,fedora-green-0))))
	  `(gnus-group-news-3-empty ((t (:foreground ,fedora-blue-2))))
	  `(gnus-group-news-3 ((t (:bold t :foreground ,fedora-green-1))))
	  `(gnus-header-name ((t (:bold t :foreground ,fedora-blue-1))))
	  `(gnus-header-subject ((t (:bold t :foreground ,fedora-pink-1))))
	  `(gnus-header-content ((t (:foreground ,fedora-pink-1))))
	  `(gnus-button ((t (:bold t :foreground ,fedora-blue-2))))
	  `(gnus-cite-1 ((t (:foreground ,fedora-blue-2))))
	  `(gnus-cite-2 ((t (:foreground ,fedora-blue-1))))
	  `(widget-button ((t (:bold t :foreground ,fedora-blue-1))))
	  ;;`(diff-header ((t (:foreground ,cool-fg))))
	  `(diff-added ((t (:bold t :foreground ,cool-green-0))))
	  `(diff-removed ((t (:bold t :foreground ,cool-red-0))))

	  `(w3m-anchor ((t (:bold t :foreground ,cool-pink-1))))
	  ))))
(provide 'color-theme-gnome-3-adwaita)
